server {
    listen 80;
    server_name hanu.cleverapp.in;

    root /var/www/hanu.cleverapp.in/current;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
